import json
import time

def json_to_netscape(json_file, output_file):
    with open(json_file, 'r') as f:
        cookies = json.load(f)

    with open(output_file, 'w') as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file is generated by yt-dlp. Do not edit.\n\n")

        for cookie in cookies:
            domain = cookie['domain']
            flag = 'TRUE' if domain.startswith('.') else 'FALSE'
            path = cookie['path']
            secure = 'TRUE' if cookie['secure'] else 'FALSE'
            expiration = int(cookie['expirationDate']) if 'expirationDate' in cookie else 0
            name = cookie['name']
            value = cookie['value']

            f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n")

json_to_netscape('cookies.json', 'cookies.txt')